### ISSUE TITLE
[Package] ebitengine-input: Input management library for ebitengine

### ISSUE THREAD

**Issue by Gamerfiend** [sedyh/awesome-ebitengine#12]
@quasilyte has made a library for input handling in Godot style for ebitengine

[Github](https://github.com/quasilyte/ebitengine-input)

**Comment by quasilyte** [comment]
It's not properly released yet.
But I'll do my best to do it in a few weeks or so. :innocent: 

Any feedback prior the release is appreciated though, since it's easier to fix something now than later.

**Comment by sedyh** [comment]
Hello everyone, yes, let's wait for the release.

**Comment by sedyh** [comment]
Last update: the author of ebitengine-input asked to wait while he prepares the library for release.

**Comment by quasilyte** [comment]
I released a `v0.8.0` to make it easier for people to test the library for their games.
Any feedback is appreciated.

The library may miss something that I never needed in my games, so it would be quite arrogant of me to release a `v1.0.0` just yet. :sweat_smile:

**Comment by sedyh** [comment]
Merged the first version from the mcarpenter622's PR.
