### ISSUE TITLE
Use original source repo for gween?

### ISSUE THREAD

**Issue by quasilyte** [sedyh/awesome-ebitengine#14]
awesome ebitengine lists gween from this repository: https://github.com/SolarLune/gween
It looks like it's a fork of https://github.com/tanema/gween which includes some recent commits.
Maybe we should list the original repository instead?
It's also possible to mention that there is a fork (but I haven't checked if they diverged or not).

**Comment by sedyh** [comment]
Yes, the original repository seems to be updated much more frequently. I'll look at it and put it in place of the fork if everything is ok.
