### ISSUE TITLE
Add roboden game to the list?

### ISSUE THREAD

**Issue by quasilyte** [sedyh/awesome-ebitengine#17]
https://github.com/quasilyte/roboden-game

**Comment by sedyh** [comment]
Can you add the following please?

- English README page.
- Instructions for launching via go run.
- Release with binaries for windows/macos/linux (optional, but would be great).
- Online demo version, if possible (i.e. link to itch.io or github pages).

From: [contribution guidelines](https://github.com/sedyh/awesome-ebitengine/blob/main/CONTRIBUTING.md).

**Comment by quasilyte** [comment]
Done.

**Comment by sedyh** [comment]
Nice, added to the list.
