### ISSUE TITLE
Rename Ebiten -> Ebitengine

### ISSUE THREAD

**Issue by hajimehoshi** [sedyh/awesome-ebitengine#9]
@sedyh Hi, thank you for managing this awesome list. Do you have a plan to rename Ebiten to Ebitengine in the document and the repository name? Thanks,

**Comment by sedyh** [comment]
Hello, yes, but I'm not sure should I change everything now or just the docks? The original repo and the domain still have an old name.

**Comment by hajimehoshi** [comment]
> I can change all repo names too, but then others have to change links to it in other sources. It is desirable that everyone change the names of their repos at the same time.

GitHub automatically redirects to the new repository name, so there should not be a problem. Or, is there any other concerns?

**Comment by sedyh** [comment]
Ok, I renamed the repo and all notes with old name.
